favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://legalconnection-dev.co.za.dedi6.cpt3.host-h.net/themes/legalconnect/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  legalconnect: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://logo1.png'
  url: ''
  use_default: 0
table_responsive: '-1'
table: ''
tooltip_placement: bottom
tooltip_trigger: click
