<?php

/**
 * @file
 * Install, update and uninstall functions for the legalc_test_updates module.
 */


use Drupal\Core\Database\Database;


/**
 * Implements hook_schema().
 *
 * Defines the database tables used by this module.
 *
 * @see hook_schema()
 *
 * @ingroup dbtng_example
 */
function legalc_test_updates_schema() {

  $schema['legalc_test1'] = array(

    'description' => 'Testing database updates.',

    'fields' => array(
      'pid' => array(
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique entry ID.',
      ),
      'var_string' => array(
        'type' => 'blob',
        'size' => 'big',
        'not null' => TRUE,
        'description' => 'Serialization of variable.',
      ),
      
    ),
    'primary key' => array('pid'),
    
  );

  return $schema;
}


/**
 * Write a line or two here about what the updates are for.
 * This is shown to users on the update.php page.
 */
function legalc_test_updates_update_8502(&$sandbox) {
    
    $spec = array(
        'description' => 'Testing database updates 2nd table.',

        'fields' => array(
          'pid' => array(
            'type' => 'serial',
            'not null' => TRUE,
            'description' => 'Primary Key: Unique entry ID.',
          ),
          'var_string' => array(
            'type' => 'blob',
            'size' => 'big',
            'not null' => TRUE,
            'description' => 'Serialization of variable.',
          ),

        ),
        'primary key' => array('pid'),
    );

    $schema = Database::getConnection()->schema();
    $schema->createTable('legalc_test2', $spec);

}